### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by joshuai96**
As mentioned in SovereignCloudStack/issues#222 the API server should be tested by unit oder behavior testing.

These test use a mocked SQL connection and fake http requests, to test the API operation handlers, as if they were called by a client.

The mocked SQL connections is used to simulated any kind of data or error returned by the databse and checks Gorms query generation against a expected query.

The fake http requests deliver request bodies to the function.

A request recorder checks for the http response, if any.

### CODE REVIEW

**Comment by master-caster** [comment]
Just an update to the PR to test zuul trigger

**Comment by master-caster** [comment]
based on the pipeline definition recheck needs to be in the comment i think

**Comment by master-caster** [comment]
do another recheck comment for testing

**Comment by master-caster** [comment]
do another recheck comment

**Comment by master-caster** [comment]
new recheck test

**Comment by joshuai96** [comment]
Recheck for zuul testing

**Comment by master-caster** [comment]
again recheck for zuul testing

**Comment by master-caster** [comment]
recheck again

**Review by joshmue — APPROVED** [review]

**Pull request merged**
